deploys:
  initial:
    ch:
      config:
        - "SECRET_TOKEN"
        - "UID"
        - "MAIN_APP_UID"
        - "G5_CLIENT_UID"
        - "HEROKU_APP_NAME"
        - "HEROKU_API_KEY"
        - "HEROKU_USERNAME"
        - "ID_RSA"
        - "G5_CONFIGURATOR_FEED_URL"
      tasks:
        - "rake db:migrate"
        - "rake deploy:tasks"
      addons:
        - "redistogo:nano"
        - "rediscloud"
        - "papertrail:choklad"
        - "memcachier:dev"
        - "pgbackups:auto-month"
    chd:
      config:
        - "SECRET_TOKEN"
        - "UID"
        - "MAIN_APP_UID"
        - "G5_CLIENT_UID"
        - "HEROKU_APP_NAME"
        - "HEROKU_API_KEY"
        - "HEROKU_USERNAME"
        - "ID_RSA"
        - "G5_CONFIGURATOR_FEED_URL"
        - "APP_DISPLAY_NAME"
      tasks:
        - "rake db:migrate"
        - "rake deploy:tasks"
      addons:
        - "redistogo:nano"
        - "rediscloud"
        - "papertrail:choklad"
        - "pgbackups:auto-month"
    cpns:
      config:
        - "SECRET_KEY_BASE"
      tasks:
        - "rake db:migrate"
      addons:
        - "papertrail:choklad"
        - "pgbackups:auto-month"
    cpas:
      config:
        - "SECRET_KEY_BASE"
      tasks:
        - "rake db:migrate"
      addons:
        - "papertrail:choklad"
        - "pgbackups:auto-month"
