deploys:
  initial:
    cms:
      config:
        - "SECRET_TOKEN"
        - "UID"
        - "MAIN_APP_UID"
        - "G5_CLIENT_UID"
        - "HEROKU_APP_NAME"
        - "HEROKU_API_KEY"
        - "HEROKU_USERNAME"
        - "ID_RSA"
        - "G5_CONFIGURATOR_FEED_URL"
        - "NEW_RELIC_APP_NAME"
        - "LAYOUT_GARDEN_URL"
        - "THEME_GARDEN_URL"
        - "WIDGET_GARDEN_URL"
        - "AWS_ACCESS_KEY_ID"
        - "AWS_SECRET_ACCESS_KEY"
        - "G5_AUTH_ENDPOINT"
        - "G5_AUTH_REDIRECT_URI"
      tasks:
        - "rake db:migrate"
        - "rake deploy:tasks"
      addons:
        - "redistogo:nano"
        - "rediscloud"
        - "papertrail:choklad"
        - "memcachier:dev"
        - "pgbackups:auto-month"
        - "newrelic:stark"
    cau:
      config:
        - "SECRET_TOKEN"
        - "UID"
        - "MAIN_APP_UID"
        - "G5_CLIENT_UID"
        - "HEROKU_APP_NAME"
        - "HEROKU_API_KEY"
        - "HEROKU_USERNAME"
        - "ID_RSA"
        - "G5_CONFIGURATOR_FEED_URL"
        - "APP_DISPLAY_NAME"
        - "NEW_RELIC_APP_NAME"
      tasks:
        - "rake db:migrate"
        - "rake deploy:tasks"
      addons:
        - "redistogo:nano"
        - "rediscloud"
        - "papertrail:choklad"
        - "pgbackups:auto-month"
        - "newrelic:stark"
    cpns:
      config:
        - "SECRET_KEY_BASE"
        - "NEW_RELIC_APP_NAME"
      tasks:
        - "rake db:migrate"
      addons:
        - "papertrail:choklad"
        - "pgbackups:auto-month"
        - "newrelic:stark"
    cpas:
      config:
        - "SECRET_KEY_BASE"
        - "NEW_RELIC_APP_NAME"
      tasks:
        - "rake db:migrate"
      addons:
        - "papertrail:choklad"
        - "pgbackups:auto-month"
        - "newrelic:stark"
